#!/bin/bash
#SBATCH --job-name=test.job
#SBATCH --output=/home/aabhilash/med_vlms/LLaVA-Med/running_files/test_out.txt
#SBATCH --error=/home/aabhilash/med_vlms/LLaVA-Med/running_files/test_err.txt
#SBATCH --time=2-00:00
#SBATCH --mem=50000
#SBATCH --gres=gpu:1

# Test CUDA compiler (not needed by deep learning people, we just use the python libraries)
#/cm/shared/apps/cuda11.1/toolkit/11.1.1/bin/nvcc -o saxpy /home/<netid>/cuda_c_code/saxpy.cu && ./saxpy

# Test nvidia-smi
nvidia-smi

echo "Running job in directory: $(pwd)"

source /home/aabhilash/miniconda3/etc/profile.d/conda.sh
# Test Python conda environment
conda activate llava-med 
/home/aabhilash/miniconda3/envs/llava-med/bin/python /home/aabhilash/med_vlms/LLaVA-Med/running_files/load_run_llava_med_2.py
