#!/bin/bash
#SBATCH --job-name=model_vqa_med_llava_med_vqa_rad_evaluation.job
#SBATCH --output=/home/aabhilash/med_vlms/llava-med-1/LLaVAMed100/running_files/llava_med_vqa_radevaluation_out.txt
#SBATCH --error=/home/aabhilash/med_vlms/llava-med-1/LLaVAMed100/running_files/llava_med_vqa_rad_evaluation_err.txt
#SBATCH --time=2-00:00
#SBATCH --mem=50000
#SBATCH --gres=gpu:1

# Test CUDA compiler (not needed by deep learning people, we just use the python libraries)
#/cm/shared/apps/cuda11.1/toolkit/11.1.1/bin/nvcc -o saxpy /home/<netid>/cuda_c_code/saxpy.cu && ./saxpy

# Test nvidia-smi
nvidia-smi

echo "Running job in directory: $(pwd)"

source /home/aabhilash/miniconda3/etc/profile.d/conda.sh
# Test Python conda environment
conda activate llava-med-1
echo "Python executable path: $(which python)"
ls
# /home/aabhilash/miniconda3/envs/llava-med-1/bin/python 
python /home/aabhilash/med_vlms/llava-med-1/LLaVAMed100/model_vqa_med_llava_med_in_vqa_rad.py --model-name  /home/aabhilash/med_vlms/llava-med-1/merged_weights/data_rad_merged_model \
    --question-file /home/aabhilash/med_vlms/datasets/filtered_datasets/test_vqa_rad.json \
    --image-folder /home/aabhilash/med_vlms/datasets/VQA_RAD/VQA_RAD\ Image\ Folder \
    --answers-file /home/aabhilash/med_vlms/llava-med-1/LLaVAMed100/running_files/llava-med-vqa-rad-test-answer-file.jsonl
