#!/bin/bash
#SBATCH --job-name=model_vqa_med_llava_med_in_evaluation.job
#SBATCH --output=/home/aabhilash/med_vlms/llava-med-1/LLaVAMed100/running_files/llava_med_in_slakeevaluation_out.txt
#SBATCH --error=/home/aabhilash/med_vlms/llava-med-1/LLaVAMed100/running_files/llava_med_in_slake_evaluation_err.txt
#SBATCH --time=2-00:00
#SBATCH --mem=50000
#SBATCH --gres=gpu:1

# Test CUDA compiler (not needed by deep learning people, we just use the python libraries)
#/cm/shared/apps/cuda11.1/toolkit/11.1.1/bin/nvcc -o saxpy /home/<netid>/cuda_c_code/saxpy.cu && ./saxpy

# Test nvidia-smi
nvidia-smi

echo "Running job in directory: $(pwd)"

source /home/aabhilash/miniconda3/etc/profile.d/conda.sh
# Test Python conda environment
conda activate llava-med-1
echo "Python executable path: $(which python)"
ls
# /home/aabhilash/miniconda3/envs/llava-med-1/bin/python 
python /home/aabhilash/med_vlms/llava-med-1/LLaVAMed100/model_vqa_med_llava_med_in_slake.py --model-name  /home/aabhilash/med_vlms/llava-med-1/merged_weights/llava_med_in_text_merged_model \
    --question-file /home/aabhilash/med_vlms/datasets/filtered_datasets/english_slake_test.json \
    --image-folder /home/aabhilash/med_vlms/datasets/Slake1.0/imgs \
    --answers-file /home/aabhilash/med_vlms/llava-med-1/LLaVAMed100/running_files/llava-med-in-test-answer-file-slake.jsonl
